/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DvAppBar {
        /**
          * @default 'DvAppBar'
         */
        "label": string;
    }
    interface DvButton {
        /**
          * Disables the button, preventing user interaction.
          * @default false
         */
        "disabled": boolean;
        /**
          * Associates the button with a form by id when rendered outside the form.
         */
        "form"?: string;
        /**
          * Expands the button to fill the full width of its container.
          * @default false
         */
        "fullWidth": boolean;
        /**
          * Fallback label content when slot is empty.
          * @default 'Button'
         */
        "label": string;
        /**
          * Programmatically focuses the button element.
         */
        "setFocus": () => Promise<void>;
        /**
          * The native button type.
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * The visual style variant of the button.
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary' | 'text';
    }
    interface DvCard {
        /**
          * @default ''
         */
        "heading": string;
    }
}
declare global {
    interface HTMLDvAppBarElement extends Components.DvAppBar, HTMLStencilElement {
    }
    var HTMLDvAppBarElement: {
        prototype: HTMLDvAppBarElement;
        new (): HTMLDvAppBarElement;
    };
    interface HTMLDvButtonElement extends Components.DvButton, HTMLStencilElement {
    }
    var HTMLDvButtonElement: {
        prototype: HTMLDvButtonElement;
        new (): HTMLDvButtonElement;
    };
    interface HTMLDvCardElement extends Components.DvCard, HTMLStencilElement {
    }
    var HTMLDvCardElement: {
        prototype: HTMLDvCardElement;
        new (): HTMLDvCardElement;
    };
    interface HTMLElementTagNameMap {
        "dv-app-bar": HTMLDvAppBarElement;
        "dv-button": HTMLDvButtonElement;
        "dv-card": HTMLDvCardElement;
    }
}
declare namespace LocalJSX {
    interface DvAppBar {
        /**
          * @default 'DvAppBar'
         */
        "label"?: string;
    }
    interface DvButton {
        /**
          * Disables the button, preventing user interaction.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Associates the button with a form by id when rendered outside the form.
         */
        "form"?: string;
        /**
          * Expands the button to fill the full width of its container.
          * @default false
         */
        "fullWidth"?: boolean;
        /**
          * Fallback label content when slot is empty.
          * @default 'Button'
         */
        "label"?: string;
        /**
          * The native button type.
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * The visual style variant of the button.
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary' | 'text';
    }
    interface DvCard {
        /**
          * @default ''
         */
        "heading"?: string;
    }

    interface DvAppBarAttributes {
        "label": string;
    }
    interface DvButtonAttributes {
        "variant": 'primary' | 'secondary' | 'text';
        "disabled": boolean;
        "fullWidth": boolean;
        "type": 'button' | 'submit' | 'reset';
        "label": string;
        "form": string;
    }
    interface DvCardAttributes {
        "heading": string;
    }

    interface IntrinsicElements {
        "dv-app-bar": Omit<DvAppBar, keyof DvAppBarAttributes> & { [K in keyof DvAppBar & keyof DvAppBarAttributes]?: DvAppBar[K] } & { [K in keyof DvAppBar & keyof DvAppBarAttributes as `attr:${K}`]?: DvAppBarAttributes[K] } & { [K in keyof DvAppBar & keyof DvAppBarAttributes as `prop:${K}`]?: DvAppBar[K] };
        "dv-button": Omit<DvButton, keyof DvButtonAttributes> & { [K in keyof DvButton & keyof DvButtonAttributes]?: DvButton[K] } & { [K in keyof DvButton & keyof DvButtonAttributes as `attr:${K}`]?: DvButtonAttributes[K] } & { [K in keyof DvButton & keyof DvButtonAttributes as `prop:${K}`]?: DvButton[K] };
        "dv-card": Omit<DvCard, keyof DvCardAttributes> & { [K in keyof DvCard & keyof DvCardAttributes]?: DvCard[K] } & { [K in keyof DvCard & keyof DvCardAttributes as `attr:${K}`]?: DvCardAttributes[K] } & { [K in keyof DvCard & keyof DvCardAttributes as `prop:${K}`]?: DvCard[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dv-app-bar": LocalJSX.IntrinsicElements["dv-app-bar"] & JSXBase.HTMLAttributes<HTMLDvAppBarElement>;
            "dv-button": LocalJSX.IntrinsicElements["dv-button"] & JSXBase.HTMLAttributes<HTMLDvButtonElement>;
            "dv-card": LocalJSX.IntrinsicElements["dv-card"] & JSXBase.HTMLAttributes<HTMLDvCardElement>;
        }
    }
}
