/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * Top application bar with named slots for left, center, and right content.
     */
    interface DvAppBar {
        /**
          * Accessible label applied to the header landmark.
          * @default ''
         */
        "label"?: string;
    }
    interface DvAvatar {
        /**
          * @default 'DvAvatar'
         */
        "label": string;
    }
    /**
     * Action button with visual variants and native form behaviors.
     */
    interface DvButton {
        /**
          * Disables the button, preventing user interaction.
          * @default false
         */
        "disabled": boolean;
        /**
          * Associates the button with a form by id when rendered outside the form.
         */
        "form"?: string;
        /**
          * Expands the button to fill the full width of its container.
          * @default false
         */
        "fullWidth": boolean;
        /**
          * Fallback label content when slot is empty.
          * @default 'Button'
         */
        "label": string;
        /**
          * Programmatically focuses the button element.
         */
        "setFocus": () => Promise<void>;
        /**
          * The native button type.
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * The visual style variant of the button.
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary' | 'text';
    }
    interface DvCard {
        /**
          * @default ''
         */
        "heading": string;
    }
    interface DvCheckbox {
        /**
          * @default 'DvCheckbox'
         */
        "label": string;
    }
    interface DvDropdown {
        /**
          * @default 'DvDropdown'
         */
        "label": string;
    }
    /**
     * Bottom page container for legal text, metadata, and secondary links.
     */
    interface DvFooter {
    }
    interface DvModal {
        /**
          * @default 'DvModal'
         */
        "label": string;
    }
    interface DvRadio {
        /**
          * @default 'DvRadio'
         */
        "label": string;
    }
    interface DvSidebar {
        /**
          * @default 'DvSidebar'
         */
        "label": string;
    }
    interface DvSidebarItem {
        /**
          * @default 'DvSidebarItem'
         */
        "label": string;
    }
    interface DvSkeleton {
        /**
          * @default 'DvSkeleton'
         */
        "label": string;
    }
    interface DvTab {
        /**
          * @default 'DvTab'
         */
        "label": string;
    }
    interface DvTabGroup {
        /**
          * @default 'DvTabGroup'
         */
        "label": string;
    }
    interface DvTextarea {
        /**
          * @default 'DvTextarea'
         */
        "label": string;
    }
    interface DvTextfield {
        /**
          * @default 'DvTextfield'
         */
        "label": string;
    }
    /**
     * Binary on/off control rendered as a switch.
     */
    interface DvToggle {
        /**
          * Whether the toggle is currently on.
          * @default false
         */
        "checked": boolean;
        /**
          * Disables interaction when true.
          * @default false
         */
        "disabled": boolean;
        /**
          * Visible label text used when no slotted content is provided.
          * @default 'DvToggle'
         */
        "label": string;
        /**
          * Name attribute forwarded to the internal checkbox input.
          * @default 'dv-toggle'
         */
        "name": string;
        /**
          * Value submitted when used in a native form and checked.
          * @default 'on'
         */
        "value": string;
    }
}
export interface DvToggleCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDvToggleElement;
}
declare global {
    /**
     * Top application bar with named slots for left, center, and right content.
     */
    interface HTMLDvAppBarElement extends Components.DvAppBar, HTMLStencilElement {
    }
    var HTMLDvAppBarElement: {
        prototype: HTMLDvAppBarElement;
        new (): HTMLDvAppBarElement;
    };
    interface HTMLDvAvatarElement extends Components.DvAvatar, HTMLStencilElement {
    }
    var HTMLDvAvatarElement: {
        prototype: HTMLDvAvatarElement;
        new (): HTMLDvAvatarElement;
    };
    /**
     * Action button with visual variants and native form behaviors.
     */
    interface HTMLDvButtonElement extends Components.DvButton, HTMLStencilElement {
    }
    var HTMLDvButtonElement: {
        prototype: HTMLDvButtonElement;
        new (): HTMLDvButtonElement;
    };
    interface HTMLDvCardElement extends Components.DvCard, HTMLStencilElement {
    }
    var HTMLDvCardElement: {
        prototype: HTMLDvCardElement;
        new (): HTMLDvCardElement;
    };
    interface HTMLDvCheckboxElement extends Components.DvCheckbox, HTMLStencilElement {
    }
    var HTMLDvCheckboxElement: {
        prototype: HTMLDvCheckboxElement;
        new (): HTMLDvCheckboxElement;
    };
    interface HTMLDvDropdownElement extends Components.DvDropdown, HTMLStencilElement {
    }
    var HTMLDvDropdownElement: {
        prototype: HTMLDvDropdownElement;
        new (): HTMLDvDropdownElement;
    };
    /**
     * Bottom page container for legal text, metadata, and secondary links.
     */
    interface HTMLDvFooterElement extends Components.DvFooter, HTMLStencilElement {
    }
    var HTMLDvFooterElement: {
        prototype: HTMLDvFooterElement;
        new (): HTMLDvFooterElement;
    };
    interface HTMLDvModalElement extends Components.DvModal, HTMLStencilElement {
    }
    var HTMLDvModalElement: {
        prototype: HTMLDvModalElement;
        new (): HTMLDvModalElement;
    };
    interface HTMLDvRadioElement extends Components.DvRadio, HTMLStencilElement {
    }
    var HTMLDvRadioElement: {
        prototype: HTMLDvRadioElement;
        new (): HTMLDvRadioElement;
    };
    interface HTMLDvSidebarElement extends Components.DvSidebar, HTMLStencilElement {
    }
    var HTMLDvSidebarElement: {
        prototype: HTMLDvSidebarElement;
        new (): HTMLDvSidebarElement;
    };
    interface HTMLDvSidebarItemElement extends Components.DvSidebarItem, HTMLStencilElement {
    }
    var HTMLDvSidebarItemElement: {
        prototype: HTMLDvSidebarItemElement;
        new (): HTMLDvSidebarItemElement;
    };
    interface HTMLDvSkeletonElement extends Components.DvSkeleton, HTMLStencilElement {
    }
    var HTMLDvSkeletonElement: {
        prototype: HTMLDvSkeletonElement;
        new (): HTMLDvSkeletonElement;
    };
    interface HTMLDvTabElement extends Components.DvTab, HTMLStencilElement {
    }
    var HTMLDvTabElement: {
        prototype: HTMLDvTabElement;
        new (): HTMLDvTabElement;
    };
    interface HTMLDvTabGroupElement extends Components.DvTabGroup, HTMLStencilElement {
    }
    var HTMLDvTabGroupElement: {
        prototype: HTMLDvTabGroupElement;
        new (): HTMLDvTabGroupElement;
    };
    interface HTMLDvTextareaElement extends Components.DvTextarea, HTMLStencilElement {
    }
    var HTMLDvTextareaElement: {
        prototype: HTMLDvTextareaElement;
        new (): HTMLDvTextareaElement;
    };
    interface HTMLDvTextfieldElement extends Components.DvTextfield, HTMLStencilElement {
    }
    var HTMLDvTextfieldElement: {
        prototype: HTMLDvTextfieldElement;
        new (): HTMLDvTextfieldElement;
    };
    interface HTMLDvToggleElementEventMap {
        "dvChange": boolean;
    }
    /**
     * Binary on/off control rendered as a switch.
     */
    interface HTMLDvToggleElement extends Components.DvToggle, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDvToggleElementEventMap>(type: K, listener: (this: HTMLDvToggleElement, ev: DvToggleCustomEvent<HTMLDvToggleElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDvToggleElementEventMap>(type: K, listener: (this: HTMLDvToggleElement, ev: DvToggleCustomEvent<HTMLDvToggleElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDvToggleElement: {
        prototype: HTMLDvToggleElement;
        new (): HTMLDvToggleElement;
    };
    interface HTMLElementTagNameMap {
        "dv-app-bar": HTMLDvAppBarElement;
        "dv-avatar": HTMLDvAvatarElement;
        "dv-button": HTMLDvButtonElement;
        "dv-card": HTMLDvCardElement;
        "dv-checkbox": HTMLDvCheckboxElement;
        "dv-dropdown": HTMLDvDropdownElement;
        "dv-footer": HTMLDvFooterElement;
        "dv-modal": HTMLDvModalElement;
        "dv-radio": HTMLDvRadioElement;
        "dv-sidebar": HTMLDvSidebarElement;
        "dv-sidebar-item": HTMLDvSidebarItemElement;
        "dv-skeleton": HTMLDvSkeletonElement;
        "dv-tab": HTMLDvTabElement;
        "dv-tab-group": HTMLDvTabGroupElement;
        "dv-textarea": HTMLDvTextareaElement;
        "dv-textfield": HTMLDvTextfieldElement;
        "dv-toggle": HTMLDvToggleElement;
    }
}
declare namespace LocalJSX {
    /**
     * Top application bar with named slots for left, center, and right content.
     */
    interface DvAppBar {
        /**
          * Accessible label applied to the header landmark.
          * @default ''
         */
        "label"?: string;
    }
    interface DvAvatar {
        /**
          * @default 'DvAvatar'
         */
        "label"?: string;
    }
    /**
     * Action button with visual variants and native form behaviors.
     */
    interface DvButton {
        /**
          * Disables the button, preventing user interaction.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Associates the button with a form by id when rendered outside the form.
         */
        "form"?: string;
        /**
          * Expands the button to fill the full width of its container.
          * @default false
         */
        "fullWidth"?: boolean;
        /**
          * Fallback label content when slot is empty.
          * @default 'Button'
         */
        "label"?: string;
        /**
          * The native button type.
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * The visual style variant of the button.
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary' | 'text';
    }
    interface DvCard {
        /**
          * @default ''
         */
        "heading"?: string;
    }
    interface DvCheckbox {
        /**
          * @default 'DvCheckbox'
         */
        "label"?: string;
    }
    interface DvDropdown {
        /**
          * @default 'DvDropdown'
         */
        "label"?: string;
    }
    /**
     * Bottom page container for legal text, metadata, and secondary links.
     */
    interface DvFooter {
    }
    interface DvModal {
        /**
          * @default 'DvModal'
         */
        "label"?: string;
    }
    interface DvRadio {
        /**
          * @default 'DvRadio'
         */
        "label"?: string;
    }
    interface DvSidebar {
        /**
          * @default 'DvSidebar'
         */
        "label"?: string;
    }
    interface DvSidebarItem {
        /**
          * @default 'DvSidebarItem'
         */
        "label"?: string;
    }
    interface DvSkeleton {
        /**
          * @default 'DvSkeleton'
         */
        "label"?: string;
    }
    interface DvTab {
        /**
          * @default 'DvTab'
         */
        "label"?: string;
    }
    interface DvTabGroup {
        /**
          * @default 'DvTabGroup'
         */
        "label"?: string;
    }
    interface DvTextarea {
        /**
          * @default 'DvTextarea'
         */
        "label"?: string;
    }
    interface DvTextfield {
        /**
          * @default 'DvTextfield'
         */
        "label"?: string;
    }
    /**
     * Binary on/off control rendered as a switch.
     */
    interface DvToggle {
        /**
          * Whether the toggle is currently on.
          * @default false
         */
        "checked"?: boolean;
        /**
          * Disables interaction when true.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Visible label text used when no slotted content is provided.
          * @default 'DvToggle'
         */
        "label"?: string;
        /**
          * Name attribute forwarded to the internal checkbox input.
          * @default 'dv-toggle'
         */
        "name"?: string;
        /**
          * Emits when the checked state changes due to user interaction.
         */
        "onDvChange"?: (event: DvToggleCustomEvent<boolean>) => void;
        /**
          * Value submitted when used in a native form and checked.
          * @default 'on'
         */
        "value"?: string;
    }

    interface DvAppBarAttributes {
        "label": string;
    }
    interface DvAvatarAttributes {
        "label": string;
    }
    interface DvButtonAttributes {
        "variant": 'primary' | 'secondary' | 'text';
        "disabled": boolean;
        "fullWidth": boolean;
        "type": 'button' | 'submit' | 'reset';
        "label": string;
        "form": string;
    }
    interface DvCardAttributes {
        "heading": string;
    }
    interface DvCheckboxAttributes {
        "label": string;
    }
    interface DvDropdownAttributes {
        "label": string;
    }
    interface DvModalAttributes {
        "label": string;
    }
    interface DvRadioAttributes {
        "label": string;
    }
    interface DvSidebarAttributes {
        "label": string;
    }
    interface DvSidebarItemAttributes {
        "label": string;
    }
    interface DvSkeletonAttributes {
        "label": string;
    }
    interface DvTabAttributes {
        "label": string;
    }
    interface DvTabGroupAttributes {
        "label": string;
    }
    interface DvTextareaAttributes {
        "label": string;
    }
    interface DvTextfieldAttributes {
        "label": string;
    }
    interface DvToggleAttributes {
        "label": string;
        "checked": boolean;
        "disabled": boolean;
        "name": string;
        "value": string;
    }

    interface IntrinsicElements {
        "dv-app-bar": Omit<DvAppBar, keyof DvAppBarAttributes> & { [K in keyof DvAppBar & keyof DvAppBarAttributes]?: DvAppBar[K] } & { [K in keyof DvAppBar & keyof DvAppBarAttributes as `attr:${K}`]?: DvAppBarAttributes[K] } & { [K in keyof DvAppBar & keyof DvAppBarAttributes as `prop:${K}`]?: DvAppBar[K] };
        "dv-avatar": Omit<DvAvatar, keyof DvAvatarAttributes> & { [K in keyof DvAvatar & keyof DvAvatarAttributes]?: DvAvatar[K] } & { [K in keyof DvAvatar & keyof DvAvatarAttributes as `attr:${K}`]?: DvAvatarAttributes[K] } & { [K in keyof DvAvatar & keyof DvAvatarAttributes as `prop:${K}`]?: DvAvatar[K] };
        "dv-button": Omit<DvButton, keyof DvButtonAttributes> & { [K in keyof DvButton & keyof DvButtonAttributes]?: DvButton[K] } & { [K in keyof DvButton & keyof DvButtonAttributes as `attr:${K}`]?: DvButtonAttributes[K] } & { [K in keyof DvButton & keyof DvButtonAttributes as `prop:${K}`]?: DvButton[K] };
        "dv-card": Omit<DvCard, keyof DvCardAttributes> & { [K in keyof DvCard & keyof DvCardAttributes]?: DvCard[K] } & { [K in keyof DvCard & keyof DvCardAttributes as `attr:${K}`]?: DvCardAttributes[K] } & { [K in keyof DvCard & keyof DvCardAttributes as `prop:${K}`]?: DvCard[K] };
        "dv-checkbox": Omit<DvCheckbox, keyof DvCheckboxAttributes> & { [K in keyof DvCheckbox & keyof DvCheckboxAttributes]?: DvCheckbox[K] } & { [K in keyof DvCheckbox & keyof DvCheckboxAttributes as `attr:${K}`]?: DvCheckboxAttributes[K] } & { [K in keyof DvCheckbox & keyof DvCheckboxAttributes as `prop:${K}`]?: DvCheckbox[K] };
        "dv-dropdown": Omit<DvDropdown, keyof DvDropdownAttributes> & { [K in keyof DvDropdown & keyof DvDropdownAttributes]?: DvDropdown[K] } & { [K in keyof DvDropdown & keyof DvDropdownAttributes as `attr:${K}`]?: DvDropdownAttributes[K] } & { [K in keyof DvDropdown & keyof DvDropdownAttributes as `prop:${K}`]?: DvDropdown[K] };
        "dv-footer": DvFooter;
        "dv-modal": Omit<DvModal, keyof DvModalAttributes> & { [K in keyof DvModal & keyof DvModalAttributes]?: DvModal[K] } & { [K in keyof DvModal & keyof DvModalAttributes as `attr:${K}`]?: DvModalAttributes[K] } & { [K in keyof DvModal & keyof DvModalAttributes as `prop:${K}`]?: DvModal[K] };
        "dv-radio": Omit<DvRadio, keyof DvRadioAttributes> & { [K in keyof DvRadio & keyof DvRadioAttributes]?: DvRadio[K] } & { [K in keyof DvRadio & keyof DvRadioAttributes as `attr:${K}`]?: DvRadioAttributes[K] } & { [K in keyof DvRadio & keyof DvRadioAttributes as `prop:${K}`]?: DvRadio[K] };
        "dv-sidebar": Omit<DvSidebar, keyof DvSidebarAttributes> & { [K in keyof DvSidebar & keyof DvSidebarAttributes]?: DvSidebar[K] } & { [K in keyof DvSidebar & keyof DvSidebarAttributes as `attr:${K}`]?: DvSidebarAttributes[K] } & { [K in keyof DvSidebar & keyof DvSidebarAttributes as `prop:${K}`]?: DvSidebar[K] };
        "dv-sidebar-item": Omit<DvSidebarItem, keyof DvSidebarItemAttributes> & { [K in keyof DvSidebarItem & keyof DvSidebarItemAttributes]?: DvSidebarItem[K] } & { [K in keyof DvSidebarItem & keyof DvSidebarItemAttributes as `attr:${K}`]?: DvSidebarItemAttributes[K] } & { [K in keyof DvSidebarItem & keyof DvSidebarItemAttributes as `prop:${K}`]?: DvSidebarItem[K] };
        "dv-skeleton": Omit<DvSkeleton, keyof DvSkeletonAttributes> & { [K in keyof DvSkeleton & keyof DvSkeletonAttributes]?: DvSkeleton[K] } & { [K in keyof DvSkeleton & keyof DvSkeletonAttributes as `attr:${K}`]?: DvSkeletonAttributes[K] } & { [K in keyof DvSkeleton & keyof DvSkeletonAttributes as `prop:${K}`]?: DvSkeleton[K] };
        "dv-tab": Omit<DvTab, keyof DvTabAttributes> & { [K in keyof DvTab & keyof DvTabAttributes]?: DvTab[K] } & { [K in keyof DvTab & keyof DvTabAttributes as `attr:${K}`]?: DvTabAttributes[K] } & { [K in keyof DvTab & keyof DvTabAttributes as `prop:${K}`]?: DvTab[K] };
        "dv-tab-group": Omit<DvTabGroup, keyof DvTabGroupAttributes> & { [K in keyof DvTabGroup & keyof DvTabGroupAttributes]?: DvTabGroup[K] } & { [K in keyof DvTabGroup & keyof DvTabGroupAttributes as `attr:${K}`]?: DvTabGroupAttributes[K] } & { [K in keyof DvTabGroup & keyof DvTabGroupAttributes as `prop:${K}`]?: DvTabGroup[K] };
        "dv-textarea": Omit<DvTextarea, keyof DvTextareaAttributes> & { [K in keyof DvTextarea & keyof DvTextareaAttributes]?: DvTextarea[K] } & { [K in keyof DvTextarea & keyof DvTextareaAttributes as `attr:${K}`]?: DvTextareaAttributes[K] } & { [K in keyof DvTextarea & keyof DvTextareaAttributes as `prop:${K}`]?: DvTextarea[K] };
        "dv-textfield": Omit<DvTextfield, keyof DvTextfieldAttributes> & { [K in keyof DvTextfield & keyof DvTextfieldAttributes]?: DvTextfield[K] } & { [K in keyof DvTextfield & keyof DvTextfieldAttributes as `attr:${K}`]?: DvTextfieldAttributes[K] } & { [K in keyof DvTextfield & keyof DvTextfieldAttributes as `prop:${K}`]?: DvTextfield[K] };
        "dv-toggle": Omit<DvToggle, keyof DvToggleAttributes> & { [K in keyof DvToggle & keyof DvToggleAttributes]?: DvToggle[K] } & { [K in keyof DvToggle & keyof DvToggleAttributes as `attr:${K}`]?: DvToggleAttributes[K] } & { [K in keyof DvToggle & keyof DvToggleAttributes as `prop:${K}`]?: DvToggle[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Top application bar with named slots for left, center, and right content.
             */
            "dv-app-bar": LocalJSX.IntrinsicElements["dv-app-bar"] & JSXBase.HTMLAttributes<HTMLDvAppBarElement>;
            "dv-avatar": LocalJSX.IntrinsicElements["dv-avatar"] & JSXBase.HTMLAttributes<HTMLDvAvatarElement>;
            /**
             * Action button with visual variants and native form behaviors.
             */
            "dv-button": LocalJSX.IntrinsicElements["dv-button"] & JSXBase.HTMLAttributes<HTMLDvButtonElement>;
            "dv-card": LocalJSX.IntrinsicElements["dv-card"] & JSXBase.HTMLAttributes<HTMLDvCardElement>;
            "dv-checkbox": LocalJSX.IntrinsicElements["dv-checkbox"] & JSXBase.HTMLAttributes<HTMLDvCheckboxElement>;
            "dv-dropdown": LocalJSX.IntrinsicElements["dv-dropdown"] & JSXBase.HTMLAttributes<HTMLDvDropdownElement>;
            /**
             * Bottom page container for legal text, metadata, and secondary links.
             */
            "dv-footer": LocalJSX.IntrinsicElements["dv-footer"] & JSXBase.HTMLAttributes<HTMLDvFooterElement>;
            "dv-modal": LocalJSX.IntrinsicElements["dv-modal"] & JSXBase.HTMLAttributes<HTMLDvModalElement>;
            "dv-radio": LocalJSX.IntrinsicElements["dv-radio"] & JSXBase.HTMLAttributes<HTMLDvRadioElement>;
            "dv-sidebar": LocalJSX.IntrinsicElements["dv-sidebar"] & JSXBase.HTMLAttributes<HTMLDvSidebarElement>;
            "dv-sidebar-item": LocalJSX.IntrinsicElements["dv-sidebar-item"] & JSXBase.HTMLAttributes<HTMLDvSidebarItemElement>;
            "dv-skeleton": LocalJSX.IntrinsicElements["dv-skeleton"] & JSXBase.HTMLAttributes<HTMLDvSkeletonElement>;
            "dv-tab": LocalJSX.IntrinsicElements["dv-tab"] & JSXBase.HTMLAttributes<HTMLDvTabElement>;
            "dv-tab-group": LocalJSX.IntrinsicElements["dv-tab-group"] & JSXBase.HTMLAttributes<HTMLDvTabGroupElement>;
            "dv-textarea": LocalJSX.IntrinsicElements["dv-textarea"] & JSXBase.HTMLAttributes<HTMLDvTextareaElement>;
            "dv-textfield": LocalJSX.IntrinsicElements["dv-textfield"] & JSXBase.HTMLAttributes<HTMLDvTextfieldElement>;
            /**
             * Binary on/off control rendered as a switch.
             */
            "dv-toggle": LocalJSX.IntrinsicElements["dv-toggle"] & JSXBase.HTMLAttributes<HTMLDvToggleElement>;
        }
    }
}
